release_branches:
  - main
  
slack:
  notify_channel:
    - expeditor-testing
   

subscriptions:
  - workload: pull_request_merged:{{github_repo}}:{{release_branch}}:*
    actions:
      - built_in:bump_version
    pull_request: true
