release_branches:
  - main
  
slack:
  notify_channel:
    - expeditor-testing

subscriptions:
  - workload: pull_request_merged:{{github_repo}}:{{release_branch}}:*
    actions:
      - bash:.expeditor/noop.sh
    pull_request: 
      title: Title goes here!
      description: Description block!
      branch: my-cool-branch
