release_branches:
  - main
  
slack:
  notify_channel:
    - expeditor-testing

subscriptions:
  - workload: pull_request_merged:{{github_repo}}:{{release_branch}}:*
    actions:
      - bash:.expeditor/noop.sh
    pull_request: 
      title: "{{title}}"
      description: .expeditor/template.mustache
      branch: my-cool-branch
